
import { Category, Rule } from './types';

export const RULES: Rule[] = [
  // 전국대회(랭킹) 입상
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 12 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 12 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 10 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 10 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 미만', birthYear: '1969년 이후', recency: '7년 미만', score: 10 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 미만', birthYear: '1969년 이후', recency: '7년 이상', score: 8 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 미만', birthYear: '1968년 이전', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_RANKING, rank: '우승', count: '5회 미만', birthYear: '1968년 이전', recency: '7년 이상', score: 8 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_RANKING, rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_RANKING, rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },

  // 전국대회(비랭킹) 입상 - 64 DRAW 초과
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 9 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 초과', rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 4 },

  // 전국대회(비랭킹) 입상 - 64 DRAW 미만
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '7년 미만', score: 8 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '7년 이상', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 미만', score: 6 },
  { category: Category.NATIONAL_NON_RANKING, subCategory: '64 DRAW 미만', rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '7년 이상', score: 4 },

  // 지역대회-마스터부
  { category: Category.LOCAL_MASTER, rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 8 },
  { category: Category.LOCAL_MASTER, rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 8 },
  { category: Category.LOCAL_MASTER, rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 8 },
  { category: Category.LOCAL_MASTER, rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 8 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 8 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_MASTER, rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_MASTER, rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 4 },

  // 지역대회-챌린저부
  { category: Category.LOCAL_CHALLENGER, rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_CHALLENGER, rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_CHALLENGER, rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_CHALLENGER, rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '2회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 6 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 6 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '2회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '1회', birthYear: '1969년 이후', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '준우승', count: '1회', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },
  { category: Category.LOCAL_CHALLENGER, rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '3위', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_CHALLENGER, rank: '3위', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },

  // 지역대회-퓨처스부
  { category: Category.LOCAL_FUTURES, rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_FUTURES, rank: '우승', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_FUTURES, rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_FUTURES, rank: '우승', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },
  { category: Category.LOCAL_FUTURES, rank: '준우승/3위', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_FUTURES, rank: '준우승/3위', count: '1회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 4 },
  { category: Category.LOCAL_FUTURES, rank: '준우승/3위', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 4 },
  { category: Category.LOCAL_FUTURES, rank: '준우승/3위', count: '1회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },

  // 전국대회(랭킹)-국화부
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '5회 이상', birthYear: '1969년 이후', recency: '5년 미만', score: 6 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '5회 이상', birthYear: '1969년 이후', recency: '5년 이상', score: 6 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '5회 이상', birthYear: '1968년 이전', recency: '5년 미만', score: 6 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '5회 이상', birthYear: '1968년 이전', recency: '5년 이상', score: 4 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '3,4회', birthYear: '1969년 이후', recency: '5년 미만', score: 4 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '3,4회', birthYear: '1969년 이후', recency: '5년 이상', score: 4 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '3,4회', birthYear: '1968년 이전', recency: '5년 미만', score: 4 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '3,4회', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '1,2회', birthYear: '1969년 이후', recency: '5년 미만', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '1,2회', birthYear: '1969년 이후', recency: '5년 이상', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '1,2회', birthYear: '1968년 이전', recency: '5년 미만', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '우승', count: '1,2회', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '준우승/3위', count: '해당없음', birthYear: '1969년 이후', recency: '5년 미만', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '준우승/3위', count: '해당없음', birthYear: '1969년 이후', recency: '5년 이상', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '준우승/3위', count: '해당없음', birthYear: '1968년 이전', recency: '5년 미만', score: 2 },
  { category: Category.NATIONAL_KOOKHWA, rank: '준우승/3위', count: '해당없음', birthYear: '1968년 이전', recency: '5년 이상', score: 2 },

  // 전국대회(개나리부)
  { category: Category.NATIONAL_GAENARI, rank: '입상(우승,준우승,3위)', count: '해당없음', birthYear: '해당없음', recency: '해당없음', score: 2 },
];
